name: dl
channels:
- defaults
- soumith
dependencies:
- anaconda=4.4.0
- python=3.5
- pytorch=0.1.12
- tqdm=4.15.0
- pip:
  - chainer==3.0.0
  - https://cntk.ai/PythonWheel/CPU-Only/cntk-2.2-cp35-cp35m-linux_x86_64.whl
  - keras==2.0.9
  - mxnet==0.12.0
  - tensorflow==1.4.0
